const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Pin,
		C3.Behaviors.Flash,
		C3.Behaviors.Platform,
		C3.Plugins.Keyboard,
		C3.Behaviors.solid,
		C3.Behaviors.Bullet,
		C3.Behaviors.Sin,
		C3.Behaviors.scrollto,
		C3.Behaviors.destroy,
		C3.Plugins.Text,
		C3.Plugins.Mouse,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Behaviors.Platform.Cnds.OnStop,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.Mouse.Cnds.OnObjectClicked
	];
};
self.C3_JsPropNameTable = [
	{Fixar: 0},
	{Piscar: 0},
	{personagem_animacoess: 0},
	{Plataforma2: 0},
	{personagem_sensor: 0},
	{Teclado: 0},
	{Sólido: 0},
	{Sprite: 0},
	{Projétil: 0},
	{bala: 0},
	{Sprite2: 0},
	{Senóide: 0},
	{virus: 0},
	{plataforma: 0},
	{parede: 0},
	{CentrarEm: 0},
	{camera: 0},
	{boss: 0},
	{Sprite4: 0},
	{DestruirForaDoLayout: 0},
	{Sprite3: 0},
	{barradevida: 0},
	{fim: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{Texto: 0},
	{voltarAoMenu: 0},
	{Mouse: 0},
	{jogar: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{Texto2: 0},
	{creditos: 0},
	{voltarCredito: 0},
	{histo2: 0},
	{histo1: 0},
	{iniciar: 0},
	{Sprite9: 0},
	{Texto3: 0},
	{jogarHistoria: 0},
	{dick: 0},
	{dickk: 0},
	{vidaprota: 0},
	{Sprite10: 0},
	{ARANHA: 0},
	{PONTOS: 0},
	{Sprite11: 0},
	{PAREWDE: 0},
	{fundoKastiel: 0},
	{Sprite12: 0},
	{Sprite13: 0},
	{Sprite14: 0},
	{Sprite15: 0},
	{Texto4: 0},
	{Sprite16: 0},
	{Sprite17: 0},
	{Texto5: 0},
	{créditosButton: 0},
	{PLAYButton: 0},
	{VIDAPROTA: 0},
	{vida: 0},
	{PONTUACAO: 0}
];

self.InstanceType = {
	personagem_animacoess: class extends self.ISpriteInstance {},
	personagem_sensor: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	Sprite: class extends self.ISpriteInstance {},
	bala: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	virus: class extends self.ISpriteInstance {},
	plataforma: class extends self.ISpriteInstance {},
	parede: class extends self.ISpriteInstance {},
	camera: class extends self.ISpriteInstance {},
	boss: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	barradevida: class extends self.ISpriteInstance {},
	fim: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {},
	voltarAoMenu: class extends self.ITextInstance {},
	Mouse: class extends self.IInstance {},
	jogar: class extends self.ITextInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Texto2: class extends self.ITextInstance {},
	creditos: class extends self.ITextInstance {},
	voltarCredito: class extends self.ITextInstance {},
	histo2: class extends self.ITextInstance {},
	histo1: class extends self.ITextInstance {},
	iniciar: class extends self.ITextInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Texto3: class extends self.ITextInstance {},
	jogarHistoria: class extends self.ITextInstance {},
	dick: class extends self.ISpriteInstance {},
	dickk: class extends self.ITextInstance {},
	vidaprota: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	ARANHA: class extends self.ISpriteInstance {},
	PONTOS: class extends self.ITextInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	PAREWDE: class extends self.ISpriteInstance {},
	fundoKastiel: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Texto4: class extends self.ITextInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	Texto5: class extends self.ITextInstance {},
	créditosButton: class extends self.ISpriteInstance {},
	PLAYButton: class extends self.ISpriteInstance {}
}